---
# tasks file for bvansomeren.freebsd-php

- name: ensure php packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ freebsd_php_packages }}"
  tags:
  - install

- name: ensure php-fpm service is enabled
  command: sysrc -f /etc/rc.conf php_fpm_enable=YES
  tags:
  - startup

- name: ensure php-fpm.conf is configured
  template:
    src: php-fpm.conf
    dest: /usr/local/etc/php-fpm.conf
    validate: php-fpm -t --fpm-config %s
  notify: restart php
  tags:
  - configure

- name: ensure php-fpm.d pools are set up
  template:
    src: pool.conf
    dest: "/usr/local/etc/php-fpm.d/{{ item.name }}.conf"
    validate: php-fpm -t --fpm-config %s
  with_items: "{{ freebsd_php_pools }}"
  notify: restart php
  tags:
  - configure

- name: ensure php.ini is setup
  copy:
    src: "/usr/local/etc/php.ini-{{ freebsd_php_ini_sample }}"
    dest: "/usr/local/etc/php.ini"
    force: no
    remote_src: yes
  notify: restart php
  tags:
  - configure

- name: ensure custom global php.ini settings are set
  ini_file:
    dest: /usr/local/etc/php.ini
    section: "{{ item.section | default('PHP') }}"
    option: "{{ item.option }}"
    value: "{{ item. value }}"
  with_items: "{{ freebsd_global_ini_settings }}"
  notify: restart php
  tags:
  - configure

- name: ensure php-fpm is started
  service:
    name: php-fpm
    state: started
  tags:
  - startup
